sudo: required
services:
  - docker
script: npm test
language: node_js
before_script:
  - docker run -d --name=nats -p 4222:4222 nats:latest
  - sleep 5
after_script:
  - docker stop nats
git:
  depth: 3
node_js:
  - "6"
  - "7"
  - "8"
env:
  - NODE_ENV=test
